### ISSUE TITLE
Labels applied on pView not visible on bView

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#1250]
Noticed this a few times today. Here's an example. Logfile attached.
[hubturbo-log - Copy.zip](https://github.com/HubTurbo/HubTurbo/files/130058/hubturbo-log.-.Copy.zip)

![image](https://cloud.githubusercontent.com/assets/1673303/13039125/5a1a78ae-d3d6-11e5-9d57-46b0a2fbc3f1.png)

**Comment by damithc** [comment]
This issue surfaces another problem.
1. I applied `priority.high` on the bView, 
2. went back to pView, which did not show any labels yet.
3. Added two more labels on pView.
4. Now pView shows `priority.high` and bView shows the other two labels (but not `priority.high`).
5. In the next refresh, pView shows the other two labels. Issue lost ``priority.high` in the process.
![image](https://cloud.githubusercontent.com/assets/1673303/13039216/451a339e-d3d7-11e5-9089-87bb03199a8f.png)

**Comment by ndt93** [comment]
* The first case is possibly a failure to update on GitHub but the exception is swallowed in the `dequeue` while loop so there is no fallback (to previous labels) or error message box. #1246 might help with this.

* The second case is a consequence of how we assign labels: A set of a labels is sent to GitHub to replace all existing labels instead of performing the actual adding/removing actions. So the `priority.high` labels was squashed when the other 2 labels were sent from the `pView`.

**Comment by ndt93** [comment]
Relevant log for first case:

>>>1745381 15/02/2016 11:19:22 ERROR RepoOpControl [pool-6-thread-1] - java.net.HttpRetryException: cannot retry due to redirection, in streaming mode
java.util.concurrent.ExecutionException: java.net.HttpRetryException: cannot retry due to redirection, in streaming mode
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source) ~[?:1.8.0_73]
	at java.util.concurrent.CompletableFuture.get(Unknown Source) ~[?:1.8.0_73]
	at backend.control.RepoOpControl.dequeue(RepoOpControl.java:106) ~[HubTurbo-3.19.0-all.jar:?]
	at backend.control.RepoOpControl.lambda$init$46(RepoOpControl.java:76) ~[HubTurbo-3.19.0-all.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_73]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_73]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]
Caused by: java.net.HttpRetryException: cannot retry due to redirection, in streaming mode
	at sun.net.www.protocol.http.HttpURLConnection.followRedirect0(Unknown Source) ~[?:1.8.0_73]
	at sun.net.www.protocol.http.HttpURLConnection.followRedirect(Unknown Source) ~[?:1.8.0_73]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:1.8.0_73]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:1.8.0_73]
	at java.net.HttpURLConnection.getResponseCode(Unknown Source) ~[?:1.8.0_73]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source) ~[?:1.8.0_73]
	at org.eclipse.egit.github.core.client.GitHubClient.sendJson(GitHubClient.java:652) ~[HubTurbo-3.19.0-all.jar:?]
	at org.eclipse.egit.github.core.client.GitHubClient.put(GitHubClient.java:791) ~[HubTurbo-3.19.0-all.jar:?]
	at org.eclipse.egit.github.core.service.LabelService.setLabels(LabelService.java:139) ~[HubTurbo-3.19.0-all.jar:?]
	at org.eclipse.egit.github.core.service.LabelService.setLabels(LabelService.java:105) ~[HubTurbo-3.19.0-all.jar:?]
	at backend.github.GitHubRepo.setLabels(GitHubRepo.java:253) ~[HubTurbo-3.19.0-all.jar:?]
	at backend.github.ReplaceIssueLabelsTask.run(ReplaceIssueLabelsTask.java:28) ~[HubTurbo-3.19.0-all.jar:?]
	... 3 more

**Comment by damithc** [comment]
Yes, the first one is due to HT failing silently when it cannot updated GitHub (it was due to repo name being changed from `teammates/repo` to `teammates/teammates`).

**Comment by damithc** [comment]
I'll create another issue for the 2nd problem.
