### ISSUE TITLE
Exception while drag-drop of card to panel

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#136]
Got this exception while trying to drag a card to a panel
```
Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at com.sun.javafx.collections.ObservableListWrapper.get(Unknown Source)
	at model.TurboIssue.getLabelReference(TurboIssue.java:159)
	at model.TurboIssue.addToLabels(TurboIssue.java:261)
	at model.TurboIssue.addLabel(TurboIssue.java:225)
	at model.TurboIssue.setLabels(TurboIssue.java:268)
	at model.TurboIssue.copyValues(TurboIssue.java:344)
	at model.TurboIssue.<init>(TurboIssue.java:298)
	at ui.SidePanel.triggerIssueEdit(SidePanel.java:87)
	at ui.IssuePanel.lambda$0(IssuePanel.java:79)
	at ui.IssuePanel$$Lambda$73/665850849.changed(Unknown Source)
	at javafx.beans.value.WeakChangeListener.changed(Unknown Source)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(Unknown Source)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at javafx.beans.property.ReadOnlyObjectWrapper$ReadOnlyPropertyImpl.fireValueChangedEvent(Unknown Source)
	at javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(Unknown Source)
	at javafx.beans.property.ObjectPropertyBase.markInvalid(Unknown Source)
	at javafx.beans.property.ObjectPropertyBase.set(Unknown Source)
	at javafx.scene.control.SelectionModel.setSelectedItem(Unknown Source)
	at javafx.scene.control.MultipleSelectionModelBase$1.invalidated(Unknown Source)
	at com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(Unknown Source)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at javafx.beans.property.ReadOnlyIntegerWrapper$ReadOnlyPropertyImpl.fireValueChangedEvent(Unknown Source)
	at javafx.beans.property.ReadOnlyIntegerWrapper.fireValueChangedEvent(Unknown Source)
	at javafx.beans.property.IntegerPropertyBase.markInvalid(Unknown Source)
	at javafx.beans.property.IntegerPropertyBase.set(Unknown Source)
	at javafx.scene.control.SelectionModel.setSelectedIndex(Unknown Source)
	at javafx.scene.control.MultipleSelectionModelBase.select(Unknown Source)
	at javafx.scene.control.MultipleSelectionModelBase.clearAndSelect(Unknown Source)
	at com.sun.javafx.scene.control.behavior.ListCellBehavior.simpleSelect(Unknown Source)
	at com.sun.javafx.scene.control.behavior.ListCellBehavior.doSelect(Unknown Source)
	at com.sun.javafx.scene.control.behavior.ListCellBehavior.mousePressed(Unknown Source)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(Unknown Source)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(Unknown Source)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.event.Event.fireEvent(Unknown Source)
	at javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at javafx.scene.Scene$MouseHandler.access$1800(Unknown Source)
	at javafx.scene.Scene.impl_processMouseEvent(Unknown Source)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.access$300(Unknown Source)
	at com.sun.glass.ui.win.WinApplication$4$1.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by damithc** [comment]
Closing because no recent occurrences
