### ISSUE TITLE
IndexOutOfBoundsException in parser

### ISSUE THREAD

**Issue by dariusf** [HubTurbo/HubTurbo#1446]
Occurs in guitests.FilterTests > countFilterTest.

```
    java.lang.IndexOutOfBoundsException: Index: 4, Size: 4
    	at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_77]
    	at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_77]
    	at filter.Parser.consume(Parser.java:75) ~[main/:?]
    	at filter.Parser.parseSortKey(Parser.java:409) ~[main/:?]
    	at filter.Parser.parseSortKeys(Parser.java:394) ~[main/:?]
    	at filter.Parser.parseQualifierContent(Parser.java:231) ~[main/:?]
    	at filter.Parser.lambda$parseQualifier$0(Parser.java:217) ~[main/:?]
    	at filter.Parser.parseSeparatedContent(Parser.java:221) ~[main/:?]
    	at filter.Parser.parseQualifier(Parser.java:217) ~[main/:?]
    	at filter.Parser.parseExpression(Parser.java:113) ~[main/:?]
    	at filter.Parser.parseConjunction(Parser.java:484) ~[main/:?]
    	at filter.Parser.parseExpression(Parser.java:148) ~[main/:?]
    	at filter.Parser.check(Parser.java:57) ~[main/:?]
    	at ui.components.FilterTextField.lambda$setup$3(FilterTextField.java:59) ~[main/:?]
    	at org.controlsfx.validation.ValidationSupport.lambda$null$251(ValidationSupport.java:285) ~[controlsfx-8.40.10.jar:8.40.10]
    	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295) ~[jfxrt.jar:?]
    	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_77]
    	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294) ~[jfxrt.jar:?]
    	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:?]
    	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[jfxrt.jar:?]
    	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139) ~[jfxrt.jar:?]
    	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
```

**Comment by damithc** [comment]
How bad is this? i.e. how soon do we need to fix it?

**Comment by dariusf** [comment]
It happens on a specific kind of parse error (when the input string ends with a comma, for example when writing a list of sorting keys). Not very common but we should fix it soon.
