### ISSUE TITLE
BrowserView gets disconnected randomly

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#302]
Clicking an issue should load the issue in the BView, but this stopped working at some point in the middle of an HT session. I had to restart HT to get it working again. First time I thought it was a fluke, but happened again today in a different computer.

**Comment by damithc** [comment]
Here's the tail end of the log file. Hard to see which part is relevant because there is no timing information in the log file.

v0.8.0.jar:?]
	at ui.labelmanagement.LabelManagementComponent.populateTree(LabelManagementComponent.java:140) [resource-v0.8.0.jar:?]
	at ui.labelmanagement.LabelManagementComponent.createTreeView(LabelManagementComponent.java:81) [resource-v0.8.0.jar:?]
	at ui.labelmanagement.LabelManagementComponent.initialise(LabelManagementComponent.java:49) [resource-v0.8.0.jar:?]
	at ui.sidepanel.SidePanel.createLabelsTab(SidePanel.java:353) [resource-v0.8.0.jar:?]
	at ui.sidepanel.SidePanel.tabLayout(SidePanel.java:226) [resource-v0.8.0.jar:?]
	at ui.sidepanel.SidePanel.changeLayout(SidePanel.java:191) [resource-v0.8.0.jar:?]
	at ui.sidepanel.SidePanel.refreshSidebarLabels(SidePanel.java:143) [resource-v0.8.0.jar:?]
	at ui.labelmanagement.LabelManagementComponent$2.lambda$0(LabelManagementComponent.java:105) [resource-v0.8.0.jar:?]
	at ui.labelmanagement.LabelManagementComponent$2$$Lambda$435/839842443.run(Unknown Source) [resource-v0.8.0.jar:?]
	at com.sun.javafx.application.PlatformImpl.lambda$null$164(Unknown Source) [jfxrt.jar:?]
	at com.sun.javafx.application.PlatformImpl$$Lambda$47/394370609.run(Unknown Source) [jfxrt.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) [?:1.8.0_20]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$165(Unknown Source) [jfxrt.jar:?]
	at com.sun.javafx.application.PlatformImpl$$Lambda$46/1555093762.run(Unknown Source) [jfxrt.jar:?]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source) [jfxrt.jar:?]
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) [jfxrt.jar:?]
	at com.sun.glass.ui.win.WinApplication.lambda$null$141(Unknown Source) [jfxrt.jar:?]
	at com.sun.glass.ui.win.WinApplication$$Lambda$37/626202354.run(Unknown Source) [jfxrt.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_20]
2015-01-04 12:37:44,505 ERROR u.TurboLabelGroup [JavaFX Application Thread] Validation Failed (422): Label resource with 'name' field already exists
org.eclipse.egit.github.core.client.RequestException: Validation Failed (422): Label resource with 'name' field already exists
	at org.eclipse.egit.github.core.client.GitHubClient.createException(GitHubClient.java:552) ~[resource-v0.8.0.jar:?]
	at service.GitHubClientExtended.createException(GitHubClientExtended.java:69) ~[resource-v0.8.0.jar:?]
	at org.eclipse.egit.github.core.client.GitHubClient.sendJson(GitHubClient.java:643) ~[resource-v0.8.0.jar:?]
	at org.eclipse.egit.github.core.client.GitHubClient.post(GitHubClient.java:757) ~[resource-v0.8.0.jar:?]
	at service.LabelServiceFixed.editLabel(LabelServiceFixed.java:88) ~[resource-v0.8.0.jar:?]
	at service.ServiceManager.editLabel(ServiceManager.java:344) ~[resource-v0.8.0.jar:?]
	at ui.TurboLabelGroup.setExclusive(TurboLabelGroup.java:87) [resource-v0.8.0.jar:?]
	at ui.labelmanagement.LabelManagementComponent.populateTree(LabelManagementComponent.java:140) [resource-v0.8.0.jar:?]
	at ui.labelmanagement.LabelManagementComponent.createTreeView(LabelManagementComponent.java:81) [resource-v0.8.0.jar:?]
	at ui.labelmanagement.LabelManagementComponent.initialise(LabelManagementComponent.java:49) [resource-v0.8.0.jar:?]
	at ui.sidepanel.SidePanel.createLabelsTab(SidePanel.java:353) [resource-v0.8.0.jar:?]
	at ui.sidepanel.SidePanel.tabLayout(SidePanel.java:226) [resource-v0.8.0.jar:?]
	at ui.sidepanel.SidePanel.changeLayout(SidePanel.java:191) [resource-v0.8.0.jar:?]
	at ui.sidepanel.SidePanel.refreshSidebarLabels(SidePanel.java:143) [resource-v0.8.0.jar:?]
	at ui.labelmanagement.LabelManagementComponent$2.lambda$0(LabelManagementComponent.java:105) [resource-v0.8.0.jar:?]
	at ui.labelmanagement.LabelManagementComponent$2$$Lambda$435/839842443.run(Unknown Source) [resource-v0.8.0.jar:?]
	at com.sun.javafx.application.PlatformImpl.lambda$null$164(Unknown Source) [jfxrt.jar:?]
	at com.sun.javafx.application.PlatformImpl$$Lambda$47/394370609.run(Unknown Source) [jfxrt.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) [?:1.8.0_20]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$165(Unknown Source) [jfxrt.jar:?]
	at com.sun.javafx.application.PlatformImpl$$Lambda$46/1555093762.run(Unknown Source) [jfxrt.jar:?]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source) [jfxrt.jar:?]
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) [jfxrt.jar:?]
	at com.sun.glass.ui.win.WinApplication.lambda$null$141(Unknown Source) [jfxrt.jar:?]
	at com.sun.glass.ui.win.WinApplication$$Lambda$37/626202354.run(Unknown Source) [jfxrt.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_20]
2015-01-04 12:37:45,534 ERROR u.TurboLabelGroup [JavaFX Application Thread] Validation Failed (422): Label resource with 'name' field already exists
org.eclipse.egit.github.core.client.RequestException: Validation Failed (422): Label resource with 'name' field already exists
	at org.eclipse.egit.github.core.client.GitHubClient.createException(GitHubClient.java:552) ~[resource-v0.8.0.jar:?]
	at service.GitHubClientExtended.createException(GitHubClientExtended.java:69) ~[resource-v0.8.0.jar:?]
	at org.eclipse.egit.github.core.client.GitHubClient.sendJson(GitHubClient.java:643) ~[resource-v0.8.0.jar:?]
	at org.eclipse.egit.github.core.client.GitHubClient.post(GitHubClient.java:757) ~[resource-v0.8.0.jar:?]
	at service.LabelServiceFixed.editLabel(LabelServiceFixed.java:88) ~[resource-v0.8.0.jar:?]
	at service.ServiceManager.editLabel(ServiceManager.java:344) ~[resource-v0.8.0.jar:?]
	at ui.TurboLabelGroup.setExclusive(TurboLabelGroup.java:87) [resource-v0.8.0.jar:?]
	at ui.labelmanagement.LabelManagementComponent.populateTree(LabelManagementComponent.java:140) [resource-v0.8.0.jar:?]
	at ui.labelmanagement.LabelManagementComponent.createTreeView(LabelManagementComponent.java:81) [resource-v0.8.0.jar:?]
	at ui.labelmanagement.LabelManagementComponent.initialise(LabelManagementComponent.java:49) [resource-v0.8.0.jar:?]
	at ui.sidepanel.SidePanel.createLabelsTab(SidePanel.java:353) [resource-v0.8.0.jar:?]
	at ui.sidepanel.SidePanel.tabLayout(SidePanel.java:226) [resource-v0.8.0.jar:?]
	at ui.sidepanel.SidePanel.changeLayout(SidePanel.java:191) [resource-v0.8.0.jar:?]
	at ui.sidepanel.SidePanel.refreshSidebarLabels(SidePanel.java:143) [resource-v0.8.0.jar:?]
	at ui.labelmanagement.LabelManagementComponent$2.lambda$0(LabelManagementComponent.java:105) [resource-v0.8.0.jar:?]
	at ui.labelmanagement.LabelManagementComponent$2$$Lambda$435/839842443.run(Unknown Source) [resource-v0.8.0.jar:?]
	at com.sun.javafx.application.PlatformImpl.lambda$null$164(Unknown Source) [jfxrt.jar:?]
	at com.sun.javafx.application.PlatformImpl$$Lambda$47/394370609.run(Unknown Source) [jfxrt.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) [?:1.8.0_20]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$165(Unknown Source) [jfxrt.jar:?]
	at com.sun.javafx.application.PlatformImpl$$Lambda$46/1555093762.run(Unknown Source) [jfxrt.jar:?]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source) [jfxrt.jar:?]
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) [jfxrt.jar:?]
	at com.sun.glass.ui.win.WinApplication.lambda$null$141(Unknown Source) [jfxrt.jar:?]
	at com.sun.glass.ui.win.WinApplication$$Lambda$37/626202354.run(Unknown Source) [jfxrt.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_20]

**Comment by damithc** [comment]
Happened again. Here's the log. 2338 is the selected issue but it is not being shown in BView.
```
2764074 10 Jan 2015 14:20:09 INFO UI [JavaFX Application Thread] - Triggered event IssueSelectedEvent
2766401 10 Jan 2015 14:20:11 INFO NavigableListView [JavaFX Application Thread] - Mouse click on issue 8
2766401 10 Jan 2015 14:20:11 INFO UI [JavaFX Application Thread] - About to trigger event IssueSelectedEvent
2766401 10 Jan 2015 14:20:11 INFO BrowserComponent [JavaFX Application Thread] - Showing issue #2338
2766402 10 Jan 2015 14:20:11 INFO UI [JavaFX Application Thread] - Triggered event IssueSelectedEvent
2772520 10 Jan 2015 14:20:17 INFO UI [pool-4-thread-1] - About to trigger event RefreshDoneEvent
```

**Comment by damithc** [comment]
Happened again. If cannot be prevented, at least have a way to recover. Currently a restart is required.
```
645018 13 Jan 2015 22:46:23 INFO UI [JavaFX Application Thread] - Triggered event IssueSelectedEvent
658513 13 Jan 2015 22:46:37 INFO UI [pool-4-thread-1] - About to trigger event RefreshDoneEvent
658514 13 Jan 2015 22:46:37 INFO UI [pool-4-thread-1] - Triggered event RefreshDoneEvent
658560 13 Jan 2015 22:46:37 INFO DataCacheFileHandler [JavaFX Application Thread] - About to write to file for repo: teammates/repo with last checked time: 2015-01-13T14:45Z
658672 13 Jan 2015 22:46:37 INFO DataCacheFileHandler [JavaFX Application Thread] - Done writing to file for repo: teammates/repo
661758 13 Jan 2015 22:46:40 INFO NavigableListView [JavaFX Application Thread] - Mouse click on issue 34
661758 13 Jan 2015 22:46:40 INFO UI [JavaFX Application Thread] - About to trigger event IssueSelectedEvent
661759 13 Jan 2015 22:46:40 INFO BrowserComponent [JavaFX Application Thread] - Showing issue #1289
661760 13 Jan 2015 22:46:40 INFO UI [JavaFX Application Thread] - Triggered event IssueSelectedEvent
664120 13 Jan 2015 22:46:43 INFO NavigableListView [JavaFX Application Thread] - Mouse click on issue 35
664121 13 Jan 2015 22:46:43 INFO UI [JavaFX Application Thread] - About to trigger event IssueSelectedEvent
664121 13 Jan 2015 22:46:43 INFO BrowserComponent [JavaFX Application Thread] - Showing issue #1287
664121 13 Jan 2015 22:46:43 INFO UI [JavaFX Application Thread] - Triggered event IssueSelectedEvent
664191 13 Jan 2015 22:46:43 INFO UI [pool-4-thread-1] - About to trigger event RefreshDoneEvent
664192 13 Jan 2015 22:46:43 INFO UI [pool-4-thread-1] - Triggered event RefreshDoneEvent
```

**Comment by damithc** [comment]
Happened again just now. The chromedriver process is still alive.

**Comment by damithc** [comment]
To detect if there is still a connection to the bView, you can try to read something from the bView.

**Comment by damithc** [comment]
Encountered again. May be put a temporary measure of restarting the bView if cannot read from it? That will cover the situation of closing the bView accidentally too.

**Comment by dariusf** [comment]
The problem is we don't know when it happens. We can't really read from the browser, only send commands to it, and when we do nothing happens, as if it's open the whole time. We're currently catching exceptions and reopening when we know that it's been closed.

**Comment by damithc** [comment]
You should be able to read from the Browser. In TEAMMATES, we do that all the time (to verify that the page has the right content).

**Comment by rd1992** [comment]
Cant reproduce the issue. Therefore implemented failsafe measures. Whenever issue is selected, check if browser window is active or whether the driver is null.

**Comment by damithc** [comment]
Is there a pull request for this?

**Comment by rd1992** [comment]
hmm. i shall create one.
