### ISSUE TITLE
Exception in log file: unexpected alert open

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#578]
Found this in logs when I was looking through the log for some other reason:
```
6826993 05 Apr 2015 11:46:47 INFO UpdateService [pool-4-thread-1] - New ETag for resource /issues: Optional[d7db1f955711eaa89cc82f2c324961f1]
6826994 05 Apr 2015 11:46:47 INFO Model [JavaFX Application Thread] - 2 issues changed/added since last sync
6826996 05 Apr 2015 11:46:47 INFO Model [JavaFX Application Thread] - Updated issue: 687
6826997 05 Apr 2015 11:46:47 INFO Model [JavaFX Application Thread] - Updated issue: 775
6827132 05 Apr 2015 11:46:47 INFO CacheFileHandler [pool-4-thread-1] - Wrote to file for repo teammates/repo with last checked time: Sun Apr 05 11:46:36 SGT 2015
6838582 05 Apr 2015 11:46:58 INFO UpdatedIssueMetadata [pool-4-thread-1] - Downloaded comments for 29 issues
6849002 05 Apr 2015 11:47:09 INFO UpdatedIssueMetadata [pool-4-thread-1] - Downloaded events for 29 issues
6849003 05 Apr 2015 11:47:09 INFO UI [pool-4-thread-1] - About to trigger event ModelChangedEvent
6849003 05 Apr 2015 11:47:09 INFO UI [pool-4-thread-1] - Triggered event ModelChangedEvent
6849217 05 Apr 2015 11:47:09 ERROR UI [JavaFX Application Thread] - unexpected alert open
  (Session info: chrome=41.0.2272.118)
  (Driver info: chromedriver=2.13.307647 (5a7d0541ebc58e69994a6fb2ed930f45261f3c29),platform=Windows NT 6.3 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 4 milliseconds: null
Build info: version: '2.44.0', revision: '76d78cf', time: '2014-10-23 20:03:00'
System info: host: 'damithch-mbpr', ip: '192.168.1.161', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_40'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={userDataDir=C:\Users\damithch\AppData\Local\Temp\scoped_dir4780_28278}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, version=41.0.2272.118, platform=WIN8_1, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 419c3b3b5b273d0504ae694802c54325
org.openqa.selenium.UnhandledAlertException: unexpected alert open
  (Session info: chrome=41.0.2272.118)
  (Driver info: chromedriver=2.13.307647 (5a7d0541ebc58e69994a6fb2ed930f45261f3c29),platform=Windows NT 6.3 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 4 milliseconds: null
Build info: version: '2.44.0', revision: '76d78cf', time: '2014-10-23 20:03:00'
System info: host: 'damithch-mbpr', ip: '192.168.1.161', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_40'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={userDataDir=C:\Users\damithch\AppData\Local\Temp\scoped_dir4780_28278}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, version=41.0.2272.118, platform=WIN8_1, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 419c3b3b5b273d0504ae694802c54325
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_40]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_40]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_40]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_40]
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204) ~[resource-v2.4.2.jar:?]
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:162) ~[resource-v2.4.2.jar:?]
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599) ~[resource-v2.4.2.jar:?]
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:508) ~[resource-v2.4.2.jar:?]
	at browserview.BrowserComponent.getCurrentPageSource(BrowserComponent.java:429) ~[resource-v2.4.2.jar:?]
	at browserview.BrowserComponent.hasBviewChanged(BrowserComponent.java:434) ~[resource-v2.4.2.jar:?]
	at ui.UI$1.lambda$0(UI.java:185) ~[resource-v2.4.2.jar:?]
	at ui.UI$1$$Lambda$513/359433415.run(Unknown Source) ~[?:?]
	at com.sun.javafx.application.PlatformImpl.lambda$null$170(Unknown Source) ~[jfxrt.jar:?]
	at com.sun.javafx.application.PlatformImpl$$Lambda$48/462578023.run(Unknown Source) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_40]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$171(Unknown Source) ~[jfxrt.jar:?]
	at com.sun.javafx.application.PlatformImpl$$Lambda$46/326549596.run(Unknown Source) ~[?:?]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source) ~[jfxrt.jar:?]
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) [jfxrt.jar:?]
	at com.sun.glass.ui.win.WinApplication.lambda$null$145(Unknown Source) [jfxrt.jar:?]
	at com.sun.glass.ui.win.WinApplication$$Lambda$36/580024961.run(Unknown Source) [jfxrt.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_40]

**Comment by rd1992** [comment]
Well its nothing to worry about. Can catch this and log it with a message.
