### ISSUE TITLE
API rate limit exceeded 

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#579]
3556526 05 Apr 2015 12:48:54 ERROR UpdatedIssueMetadata [pool-4-thread-1] - API rate limit exceeded for abc. (403)
org.eclipse.egit.github.core.client.RequestException: API rate limit exceeded for damithc. (403)
	at org.eclipse.egit.github.core.client.GitHubClient.createException(GitHubClient.java:552) ~[resource-v2.4.2.jar:?]
	at service.GitHubClientExtended.createException(GitHubClientExtended.java:111) ~[resource-v2.4.2.jar:?]
	at service.GitHubClientExtended.getEvent(GitHubClientExtended.java:102) ~[resource-v2.4.2.jar:?]
	at service.IssueServiceExtended.getIssueEvents(IssueServiceExtended.java:155) ~[resource-v2.4.2.jar:?]
	at service.ServiceManager.getEvents(ServiceManager.java:769) ~[resource-v2.4.2.jar:?]
	at service.UpdatedIssueMetadata.downloadEvents(UpdatedIssueMetadata.java:35) [resource-v2.4.2.jar:?]
	at service.UpdatedIssueMetadata.download(UpdatedIssueMetadata.java:26) [resource-v2.4.2.jar:?]
	at service.ServiceManager.preventRepoSwitchingAndUpdateModel(ServiceManager.java:423) [resource-v2.4.2.jar:?]
	at service.ServiceManager.lambda$0(ServiceManager.java:399) [resource-v2.4.2.jar:?]
	at service.ServiceManager$$Lambda$94/1838798335.run(Unknown Source) [resource-v2.4.2.jar:?]
	at service.TickingTimer.lambda$0(TickingTimer.java:122) [resource-v2.4.2.jar:?]
	at service.TickingTimer$$Lambda$407/575147005.run(Unknown Source) [resource-v2.4.2.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_40]
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:1.8.0_40]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [?:1.8.0_40]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_40]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_40]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_40]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_40]

**Comment by damithc** [comment]
Did they started throttling due to recent DDoS attacks? What's the current cap? How to overcome this limit?

**Comment by damithc** [comment]
BTW, after this happens, some issues go out of sync with the remote repo. We should not update the 'last updated' time if we encounter 'APT limit' error.

**Comment by dariusf** [comment]
No throttling, cap is still the same at 5000 per hour. This limit is the maximum GitHub offers on a non-discretionary basis.

From the stack trace, we are probably hitting the limit because we get comments and event information on every refresh. Did you have a lot of issues in an `updated` filter?

One way I can think of to solve this would be to use conditional requests/an ETag *per issue*. Same strategy as how the recent API problems were solved. Have to test to see if this works.

**Comment by damithc** [comment]
I had HT open in both my comps, so that could have been a factor too. We still have to handle the error properly if it happens.
