### ISSUE TITLE
Panel UI messed up

### ISSUE THREAD

**Issue by damithc** [HubTurbo/HubTurbo#934]
This happened today
![image](https://cloud.githubusercontent.com/assets/1673303/9647329/7ad393f4-520e-11e5-9295-21a335fb929a.png)

**Comment by damithc** [comment]
It went away after I restarted.

**Comment by acruis** [comment]
I got a variant of this yesterday too, but there was absolutely no text at all.

**Comment by damithc** [comment]
Did we switch to a new JavaFX version recently?

**Comment by acruis** [comment]
Nope.

**Comment by dariusf** [comment]
We should check the log. This can happen if there's an uncaught exception during initialisation.

**Comment by damithc** [comment]
I see. I'll check the log next time this happens.

**Comment by HansNewbie** [comment]
Just for reference; I got the variant where no text at all, but only for first panel. The second panel shows up just fine. In the log I got:
```
367216 12/10/2015 23:42:36 ERROR UI [JavaFX Application Thread] - No value present
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_51]
	at ui.listpanel.ListPanelCell.updateItem(ListPanelCell.java:42) ~[main/:?]
	at ui.listpanel.ListPanelCell.updateItem(ListPanelCell.java:13) ~[main/:?]
	at javafx.scene.control.ListCell.updateItem(ListCell.java:471) ~[jfxrt.jar:?]
	at javafx.scene.control.ListCell.indexChanged(ListCell.java:330) ~[jfxrt.jar:?]
	at javafx.scene.control.IndexedCell.updateIndex(IndexedCell.java:116) ~[jfxrt.jar:?]
	at com.sun.javafx.scene.control.skin.VirtualFlow.setCellIndex(VirtualFlow.java:1950) ~[jfxrt.jar:?]
	at com.sun.javafx.scene.control.skin.VirtualFlow.addTrailingCells(VirtualFlow.java:1344) ~[jfxrt.jar:?]
	at com.sun.javafx.scene.control.skin.VirtualFlow.adjustPixels(VirtualFlow.java:2380) ~[jfxrt.jar:?]
	at com.sun.javafx.scene.control.skin.VirtualFlow$2.handle(VirtualFlow.java:589) ~[jfxrt.jar:?]
	at com.sun.javafx.scene.control.skin.VirtualFlow$2.handle(VirtualFlow.java:531) ~[jfxrt.jar:?]
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86) ~[jfxrt.jar:?]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238) ~[jfxrt.jar:?]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191) ~[jfxrt.jar:?]
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59) ~[jfxrt.jar:?]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58) ~[jfxrt.jar:?]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[jfxrt.jar:?]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) ~[jfxrt.jar:?]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[jfxrt.jar:?]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) ~[jfxrt.jar:?]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[jfxrt.jar:?]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) ~[jfxrt.jar:?]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[jfxrt.jar:?]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) ~[jfxrt.jar:?]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[jfxrt.jar:?]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) ~[jfxrt.jar:?]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[jfxrt.jar:?]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) ~[jfxrt.jar:?]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[jfxrt.jar:?]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) ~[jfxrt.jar:?]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[jfxrt.jar:?]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) ~[jfxrt.jar:?]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[jfxrt.jar:?]
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74) ~[jfxrt.jar:?]
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54) ~[jfxrt.jar:?]
	at javafx.event.Event.fireEvent(Event.java:198) ~[jfxrt.jar:?]
	at javafx.scene.Scene.processGestureEvent(Scene.java:1840) ~[jfxrt.jar:?]
	at javafx.scene.Scene.access$300(Scene.java:159) ~[jfxrt.jar:?]
	at javafx.scene.Scene$ScenePeerListener.scrollEvent(Scene.java:2573) ~[jfxrt.jar:?]
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$null$365(GlassViewEventHandler.java:852) ~[jfxrt.jar:?]
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$$Lambda$625/859383525.run(Unknown Source) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_51]
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleScrollGestureEvent$366(GlassViewEventHandler.java:836) ~[jfxrt.jar:?]
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$$Lambda$624/208628452.get(Unknown Source) ~[?:?]
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:404) ~[jfxrt.jar:?]
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleScrollGestureEvent(GlassViewEventHandler.java:835) ~[jfxrt.jar:?]
	at com.sun.glass.ui.View.handleScrollGestureEvent(View.java:597) ~[jfxrt.jar:?]
	at com.sun.glass.ui.View.notifyScrollGestureEvent(View.java:1054) ~[jfxrt.jar:?]
	at com.sun.glass.ui.GestureSupport.handleDeltaScrolling(GestureSupport.java:338) ~[jfxrt.jar:?]
	at com.sun.glass.ui.mac.MacGestureSupport.scrollGesturePerformed(MacGestureSupport.java:116) ~[jfxrt.jar:?]
```
I found it when I removed a repo then change repository. I can't reproduce it, and I don't think it stems from removing repo since this issue starts on Sep 3 but remove-repo only merged on Sep 9 (#940)
